CREATE TABLE passenger(
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(MAX) NOT NULL,
    sex VARCHAR(7) NOT NULL,
    age DOUBLE PRECISION,
    sibsp INT NOT NULL,
    parch INT NOT NULL 
);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (892,'Kelly, Mr. James','male',34.5,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (893,'Wilkes, Mrs. James (Ellen Needs)','female',47,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (894,'Myles, Mr. Thomas Francis','male',62,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (895,'Wirz, Mr. Albert','male',27,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (896,'Hirvonen, Mrs. Alexander (Helga E Lindqvist)','female',22,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (897,'Svensson, Mr. Johan Cervin','male',14,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (898,'Connolly, Miss. Kate','female',30,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (899,'Caldwell, Mr. Albert Francis','male',26,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (900,'Abrahim, Mrs. Joseph (Sophie Halaut Easu)','female',18,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (901,'Davies, Mr. John Samuel','male',21,2,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (902,'Ilieff, Mr. Ylio','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (903,'Jones, Mr. Charles Cresson','male',46,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (904,'Snyder, Mrs. John Pillsbury (Nelle Stevenson)','female',23,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (905,'Howard, Mr. Benjamin','male',63,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (906,'Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)','female',47,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (907,'del Carlo, Mrs. Sebastiano (Argenia Genovesi)','female',24,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (908,'Keane, Mr. Daniel','male',35,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (909,'Assaf, Mr. Gerios','male',21,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (910,'Ilmakangas, Miss. Ida Livija','female',27,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (911,'Assaf Khalil, Mrs. Mariana (Miriam")"','female',45,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (912,'Rothschild, Mr. Martin','male',55,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (913,'Olsen, Master. Artur Karl','male',9,0,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (914,'Flegenheim, Mrs. Alfred (Antoinette)','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (915,'Williams, Mr. Richard Norris II','male',21,0,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (916,'Ryerson, Mrs. Arthur Larned (Emily Maria Borie)','female',48,1,3);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (917,'Robins, Mr. Alexander A','male',50,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (918,'Ostby, Miss. Helene Ragnhild','female',22,0,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (919,'Daher, Mr. Shedid','male',22.5,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (920,'Brady, Mr. John Bertram','male',41,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (921,'Samaan, Mr. Elias','male',,2,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (922,'Louch, Mr. Charles Alexander','male',50,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (923,'Jefferys, Mr. Clifford Thomas','male',24,2,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (924,'Dean, Mrs. Bertram (Eva Georgetta Light)','female',33,1,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (925,'Johnston, Mrs. Andrew G (Elizabeth Lily" Watson)"','female',,1,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (926,'Mock, Mr. Philipp Edmund','male',30,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (927,'Katavelas, Mr. Vassilios (Catavelas Vassilios")"','male',18.5,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (928,'Roth, Miss. Sarah A','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (929,'Cacic, Miss. Manda','female',21,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (930,'Sap, Mr. Julius','male',25,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (931,'Hee, Mr. Ling','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (932,'Karun, Mr. Franz','male',39,0,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (933,'Franklin, Mr. Thomas Parham','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (934,'Goldsmith, Mr. Nathan','male',41,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (935,'Corbett, Mrs. Walter H (Irene Colvin)','female',30,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (936,'Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)','female',45,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (937,'Peltomaki, Mr. Nikolai Johannes','male',25,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (938,'Chevre, Mr. Paul Romaine','male',45,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (939,'Shaughnessy, Mr. Patrick','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (940,'Bucknell, Mrs. William Robert (Emma Eliza Ward)','female',60,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (941,'Coutts, Mrs. William (Winnie Minnie" Treanor)"','female',36,0,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (942,'Smith, Mr. Lucien Philip','male',24,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (943,'Pulbaum, Mr. Franz','male',27,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (944,'Hocking, Miss. Ellen Nellie""','female',20,2,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (945,'Fortune, Miss. Ethel Flora','female',28,3,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (946,'Mangiavacchi, Mr. Serafino Emilio','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (947,'Rice, Master. Albert','male',10,4,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (948,'Cor, Mr. Bartol','male',35,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (949,'Abelseth, Mr. Olaus Jorgensen','male',25,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (950,'Davison, Mr. Thomas Henry','male',,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (951,'Chaudanson, Miss. Victorine','female',36,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (952,'Dika, Mr. Mirko','male',17,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (953,'McCrae, Mr. Arthur Gordon','male',32,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (954,'Bjorklund, Mr. Ernst Herbert','male',18,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (955,'Bradley, Miss. Bridget Delia','female',22,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (956,'Ryerson, Master. John Borie','male',13,2,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (957,'Corey, Mrs. Percy C (Mary Phyllis Elizabeth Miller)','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (958,'Burns, Miss. Mary Delia','female',18,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (959,'Moore, Mr. Clarence Bloomfield','male',47,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (960,'Tucker, Mr. Gilbert Milligan Jr','male',31,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (961,'Fortune, Mrs. Mark (Mary McDougald)','female',60,1,4);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (962,'Mulvihill, Miss. Bertha E','female',24,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (963,'Minkoff, Mr. Lazar','male',21,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (964,'Nieminen, Miss. Manta Josefina','female',29,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (965,'Ovies y Rodriguez, Mr. Servando','male',28.5,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (966,'Geiger, Miss. Amalie','female',35,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (967,'Keeping, Mr. Edwin','male',32.5,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (968,'Miles, Mr. Frank','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (969,'Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)','female',55,2,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (970,'Aldworth, Mr. Charles Augustus','male',30,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (971,'Doyle, Miss. Elizabeth','female',24,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (972,'Boulos, Master. Akar','male',6,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (973,'Straus, Mr. Isidor','male',67,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (974,'Case, Mr. Howard Brown','male',49,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (975,'Demetri, Mr. Marinko','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (976,'Lamb, Mr. John Joseph','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (977,'Khalil, Mr. Betros','male',,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (978,'Barry, Miss. Julia','female',27,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (979,'Badman, Miss. Emily Louisa','female',18,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (980,'O'Donoghue, Ms. Bridget','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (981,'Wells, Master. Ralph Lester','male',2,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (982,'Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judith Andersson)','female',22,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (983,'Pedersen, Mr. Olaf','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (984,'Davidson, Mrs. Thornton (Orian Hays)','female',27,1,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (985,'Guest, Mr. Robert','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (986,'Birnbaum, Mr. Jakob','male',25,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (987,'Tenglin, Mr. Gunnar Isidor','male',25,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (988,'Cavendish, Mrs. Tyrell William (Julia Florence Siegel)','female',76,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (989,'Makinen, Mr. Kalle Edvard','male',29,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (990,'Braf, Miss. Elin Ester Maria','female',20,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (991,'Nancarrow, Mr. William Henry','male',33,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (992,'Stengel, Mrs. Charles Emil Henry (Annie May Morris)','female',43,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (993,'Weisz, Mr. Leopold','male',27,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (994,'Foley, Mr. William','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (995,'Johansson Palmquist, Mr. Oskar Leander','male',26,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (996,'Thomas, Mrs. Alexander (Thamine Thelma")"','female',16,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (997,'Holthen, Mr. Johan Martin','male',28,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (998,'Buckley, Mr. Daniel','male',21,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (999,'Ryan, Mr. Edward','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1000,'Willer, Mr. Aaron (Abi Weller")"','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1001,'Swane, Mr. George','male',18.5,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1002,'Stanton, Mr. Samuel Ward','male',41,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1003,'Shine, Miss. Ellen Natalia','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1004,'Evans, Miss. Edith Corse','female',36,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1005,'Buckley, Miss. Katherine','female',18.5,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1006,'Straus, Mrs. Isidor (Rosalie Ida Blun)','female',63,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1007,'Chronopoulos, Mr. Demetrios','male',18,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1008,'Thomas, Mr. John','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1009,'Sandstrom, Miss. Beatrice Irene','female',1,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1010,'Beattie, Mr. Thomson','male',36,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1011,'Chapman, Mrs. John Henry (Sara Elizabeth Lawry)','female',29,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1012,'Watt, Miss. Bertha J','female',12,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1013,'Kiernan, Mr. John','male',,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1014,'Schabert, Mrs. Paul (Emma Mock)','female',35,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1015,'Carver, Mr. Alfred John','male',28,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1016,'Kennedy, Mr. John','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1017,'Cribb, Miss. Laura Alice','female',17,0,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1018,'Brobeck, Mr. Karl Rudolf','male',22,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1019,'McCoy, Miss. Alicia','female',,2,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1020,'Bowenur, Mr. Solomon','male',42,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1021,'Petersen, Mr. Marius','male',24,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1022,'Spinner, Mr. Henry John','male',32,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1023,'Gracie, Col. Archibald IV','male',53,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1024,'Lefebre, Mrs. Frank (Frances)','female',,0,4);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1025,'Thomas, Mr. Charles P','male',,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1026,'Dintcheff, Mr. Valtcho','male',43,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1027,'Carlsson, Mr. Carl Robert','male',24,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1028,'Zakarian, Mr. Mapriededer','male',26.5,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1029,'Schmidt, Mr. August','male',26,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1030,'Drapkin, Miss. Jennie','female',23,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1031,'Goodwin, Mr. Charles Frederick','male',40,1,6);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1032,'Goodwin, Miss. Jessie Allis','female',10,5,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1033,'Daniels, Miss. Sarah','female',33,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1034,'Ryerson, Mr. Arthur Larned','male',61,1,3);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1035,'Beauchamp, Mr. Henry James','male',28,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1036,'Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lingrey")"','male',42,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1037,'Vander Planke, Mr. Julius','male',31,3,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1038,'Hilliard, Mr. Herbert Henry','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1039,'Davies, Mr. Evan','male',22,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1040,'Crafton, Mr. John Bertram','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1041,'Lahtinen, Rev. William','male',30,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1042,'Earnshaw, Mrs. Boulton (Olive Potter)','female',23,0,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1043,'Matinoff, Mr. Nicola','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1044,'Storey, Mr. Thomas','male',60.5,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1045,'Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)','female',36,0,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1046,'Asplund, Master. Filip Oscar','male',13,4,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1047,'Duquemin, Mr. Joseph','male',24,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1048,'Bird, Miss. Ellen','female',29,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1049,'Lundin, Miss. Olga Elida','female',23,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1050,'Borebank, Mr. John James','male',42,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1051,'Peacock, Mrs. Benjamin (Edith Nile)','female',26,0,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1052,'Smyth, Miss. Julia','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1053,'Touma, Master. Georges Youssef','male',7,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1054,'Wright, Miss. Marion','female',26,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1055,'Pearce, Mr. Ernest','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1056,'Peruschitz, Rev. Joseph Maria','male',41,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1057,'Kink-Heilmann, Mrs. Anton (Luise Heilmann)','female',26,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1058,'Brandeis, Mr. Emil','male',48,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1059,'Ford, Mr. Edward Watson','male',18,2,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1060,'Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1061,'Hellstrom, Miss. Hilda Maria','female',22,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1062,'Lithman, Mr. Simon','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1063,'Zakarian, Mr. Ortin','male',27,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1064,'Dyker, Mr. Adolf Fredrik','male',23,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1065,'Torfa, Mr. Assad','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1066,'Asplund, Mr. Carl Oscar Vilhelm Gustafsson','male',40,1,5);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1067,'Brown, Miss. Edith Eileen','female',15,0,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1068,'Sincock, Miss. Maude','female',20,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1069,'Stengel, Mr. Charles Emil Henry','male',54,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1070,'Becker, Mrs. Allen Oliver (Nellie E Baumgardner)','female',36,0,3);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1071,'Compton, Mrs. Alexander Taylor (Mary Eliza Ingersoll)','female',64,0,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1072,'McCrie, Mr. James Matthew','male',30,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1073,'Compton, Mr. Alexander Taylor Jr','male',37,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1074,'Marvin, Mrs. Daniel Warner (Mary Graham Carmichael Farquarson)','female',18,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1075,'Lane, Mr. Patrick','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1076,'Douglas, Mrs. Frederick Charles (Mary Helene Baxter)','female',27,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1077,'Maybery, Mr. Frank Hubert','male',40,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1078,'Phillips, Miss. Alice Frances Louisa','female',21,0,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1079,'Davies, Mr. Joseph','male',17,2,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1080,'Sage, Miss. Ada','female',,8,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1081,'Veal, Mr. James','male',40,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1082,'Angle, Mr. William A','male',34,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1083,'Salomon, Mr. Abraham L','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1084,'van Billiard, Master. Walter John','male',11.5,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1085,'Lingane, Mr. John','male',61,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1086,'Drew, Master. Marshall Brines','male',8,0,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1087,'Karlsson, Mr. Julius Konrad Eugen','male',33,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1088,'Spedden, Master. Robert Douglas','male',6,0,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1089,'Nilsson, Miss. Berta Olivia','female',18,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1090,'Baimbrigge, Mr. Charles Robert','male',23,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1091,'Rasmussen, Mrs. (Lena Jacobsen Solvang)','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1092,'Murphy, Miss. Nora','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1093,'Danbom, Master. Gilbert Sigvard Emanuel','male',0.33,0,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1094,'Astor, Col. John Jacob','male',47,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1095,'Quick, Miss. Winifred Vera','female',8,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1096,'Andrew, Mr. Frank Thomas','male',25,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1097,'Omont, Mr. Alfred Fernand','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1098,'McGowan, Miss. Katherine','female',35,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1099,'Collett, Mr. Sidney C Stuart','male',24,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1100,'Rosenbaum, Miss. Edith Louise','female',33,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1101,'Delalic, Mr. Redjo','male',25,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1102,'Andersen, Mr. Albert Karvin','male',32,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1103,'Finoli, Mr. Luigi','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1104,'Deacon, Mr. Percy William','male',17,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1105,'Howard, Mrs. Benjamin (Ellen Truelove Arman)','female',60,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1106,'Andersson, Miss. Ida Augusta Margareta','female',38,4,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1107,'Head, Mr. Christopher','male',42,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1108,'Mahon, Miss. Bridget Delia','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1109,'Wick, Mr. George Dennick','male',57,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1110,'Widener, Mrs. George Dunton (Eleanor Elkins)','female',50,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1111,'Thomson, Mr. Alexander Morrison','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1112,'Duran y More, Miss. Florentina','female',30,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1113,'Reynolds, Mr. Harold J','male',21,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1114,'Cook, Mrs. (Selena Rogers)','female',22,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1115,'Karlsson, Mr. Einar Gervasius','male',21,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1116,'Candee, Mrs. Edward (Helen Churchill Hungerford)','female',53,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1117,'Moubarek, Mrs. George (Omine Amenia" Alexander)"','female',,0,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1118,'Asplund, Mr. Johan Charles','male',23,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1119,'McNeill, Miss. Bridget','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1120,'Everett, Mr. Thomas James','male',40.5,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1121,'Hocking, Mr. Samuel James Metcalfe','male',36,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1122,'Sweet, Mr. George Frederick','male',14,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1123,'Willard, Miss. Constance','female',21,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1124,'Wiklund, Mr. Karl Johan','male',21,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1125,'Linehan, Mr. Michael','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1126,'Cumings, Mr. John Bradley','male',39,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1127,'Vendel, Mr. Olof Edvin','male',20,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1128,'Warren, Mr. Frank Manley','male',64,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1129,'Baccos, Mr. Raffull','male',20,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1130,'Hiltunen, Miss. Marta','female',18,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1131,'Douglas, Mrs. Walter Donald (Mahala Dutton)','female',48,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1132,'Lindstrom, Mrs. Carl Johan (Sigrid Posse)','female',55,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1133,'Christy, Mrs. (Alice Frances)','female',45,0,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1134,'Spedden, Mr. Frederic Oakley','male',45,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1135,'Hyman, Mr. Abraham','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1136,'Johnston, Master. William Arthur Willie""','male',,1,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1137,'Kenyon, Mr. Frederick R','male',41,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1138,'Karnes, Mrs. J Frank (Claire Bennett)','female',22,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1139,'Drew, Mr. James Vivian','male',42,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1140,'Hold, Mrs. Stephen (Annie Margaret Hill)','female',29,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1141,'Khalil, Mrs. Betros (Zahie Maria" Elias)"','female',,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1142,'West, Miss. Barbara J','female',0.92,1,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1143,'Abrahamsson, Mr. Abraham August Johannes','male',20,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1144,'Clark, Mr. Walter Miller','male',27,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1145,'Salander, Mr. Karl Johan','male',24,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1146,'Wenzel, Mr. Linhart','male',32.5,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1147,'MacKay, Mr. George William','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1148,'Mahon, Mr. John','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1149,'Niklasson, Mr. Samuel','male',28,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1150,'Bentham, Miss. Lilian W','female',19,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1151,'Midtsjo, Mr. Karl Albert','male',21,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1152,'de Messemaeker, Mr. Guillaume Joseph','male',36.5,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1153,'Nilsson, Mr. August Ferdinand','male',21,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1154,'Wells, Mrs. Arthur Henry (Addie" Dart Trevaskis)"','female',29,0,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1155,'Klasen, Miss. Gertrud Emilia','female',1,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1156,'Portaluppi, Mr. Emilio Ilario Giuseppe','male',30,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1157,'Lyntakoff, Mr. Stanko','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1158,'Chisholm, Mr. Roderick Robert Crispin','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1159,'Warren, Mr. Charles William','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1160,'Howard, Miss. May Elizabeth','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1161,'Pokrnic, Mr. Mate','male',17,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1162,'McCaffry, Mr. Thomas Francis','male',46,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1163,'Fox, Mr. Patrick','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1164,'Clark, Mrs. Walter Miller (Virginia McDowell)','female',26,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1165,'Lennon, Miss. Mary','female',,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1166,'Saade, Mr. Jean Nassr','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1167,'Bryhl, Miss. Dagmar Jenny Ingeborg ','female',20,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1168,'Parker, Mr. Clifford Richard','male',28,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1169,'Faunthorpe, Mr. Harry','male',40,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1170,'Ware, Mr. John James','male',30,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1171,'Oxenham, Mr. Percy Thomas','male',22,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1172,'Oreskovic, Miss. Jelka','female',23,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1173,'Peacock, Master. Alfred Edward','male',0.75,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1174,'Fleming, Miss. Honora','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1175,'Touma, Miss. Maria Youssef','female',9,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1176,'Rosblom, Miss. Salli Helena','female',2,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1177,'Dennis, Mr. William','male',36,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1178,'Franklin, Mr. Charles (Charles Fardon)','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1179,'Snyder, Mr. John Pillsbury','male',24,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1180,'Mardirosian, Mr. Sarkis','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1181,'Ford, Mr. Arthur','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1182,'Rheims, Mr. George Alexander Lucien','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1183,'Daly, Miss. Margaret Marcella Maggie""','female',30,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1184,'Nasr, Mr. Mustafa','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1185,'Dodge, Dr. Washington','male',53,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1186,'Wittevrongel, Mr. Camille','male',36,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1187,'Angheloff, Mr. Minko','male',26,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1188,'Laroche, Miss. Louise','female',1,1,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1189,'Samaan, Mr. Hanna','male',,2,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1190,'Loring, Mr. Joseph Holland','male',30,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1191,'Johansson, Mr. Nils','male',29,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1192,'Olsson, Mr. Oscar Wilhelm','male',32,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1193,'Malachard, Mr. Noel','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1194,'Phillips, Mr. Escott Robert','male',43,0,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1195,'Pokrnic, Mr. Tome','male',24,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1196,'McCarthy, Miss. Catherine Katie""','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1197,'Crosby, Mrs. Edward Gifford (Catherine Elizabeth Halstead)','female',64,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1198,'Allison, Mr. Hudson Joshua Creighton','male',30,1,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1199,'Aks, Master. Philip Frank','male',0.83,0,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1200,'Hays, Mr. Charles Melville','male',55,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1201,'Hansen, Mrs. Claus Peter (Jennie L Howard)','female',45,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1202,'Cacic, Mr. Jego Grga','male',18,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1203,'Vartanian, Mr. David','male',22,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1204,'Sadowitz, Mr. Harry','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1205,'Carr, Miss. Jeannie','female',37,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1206,'White, Mrs. John Stuart (Ella Holmes)','female',55,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1207,'Hagardon, Miss. Kate','female',17,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1208,'Spencer, Mr. William Augustus','male',57,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1209,'Rogers, Mr. Reginald Harry','male',19,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1210,'Jonsson, Mr. Nils Hilding','male',27,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1211,'Jefferys, Mr. Ernest Wilfred','male',22,2,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1212,'Andersson, Mr. Johan Samuel','male',26,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1213,'Krekorian, Mr. Neshan','male',25,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1214,'Nesson, Mr. Israel','male',26,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1215,'Rowe, Mr. Alfred G','male',33,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1216,'Kreuchen, Miss. Emilie','female',39,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1217,'Assam, Mr. Ali','male',23,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1218,'Becker, Miss. Ruth Elizabeth','female',12,2,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1219,'Rosenshine, Mr. George (Mr George Thorne")"','male',46,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1220,'Clarke, Mr. Charles Valentine','male',29,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1221,'Enander, Mr. Ingvar','male',21,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1222,'Davies, Mrs. John Morgan (Elizabeth Agnes Mary White) ','female',48,0,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1223,'Dulles, Mr. William Crothers','male',39,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1224,'Thomas, Mr. Tannous','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1225,'Nakid, Mrs. Said (Waika Mary" Mowad)"','female',19,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1226,'Cor, Mr. Ivan','male',27,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1227,'Maguire, Mr. John Edward','male',30,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1228,'de Brito, Mr. Jose Joaquim','male',32,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1229,'Elias, Mr. Joseph','male',39,0,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1230,'Denbury, Mr. Herbert','male',25,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1231,'Betros, Master. Seman','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1232,'Fillbrook, Mr. Joseph Charles','male',18,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1233,'Lundstrom, Mr. Thure Edvin','male',32,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1234,'Sage, Mr. John George','male',,1,9);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1235,'Cardeza, Mrs. James Warburton Martinez (Charlotte Wardle Drake)','female',58,0,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1236,'van Billiard, Master. James William','male',,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1237,'Abelseth, Miss. Karen Marie','female',16,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1238,'Botsford, Mr. William Hull','male',26,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1239,'Whabee, Mrs. George Joseph (Shawneene Abi-Saab)','female',38,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1240,'Giles, Mr. Ralph','male',24,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1241,'Walcroft, Miss. Nellie','female',31,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1242,'Greenfield, Mrs. Leo David (Blanche Strouse)','female',45,0,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1243,'Stokes, Mr. Philip Joseph','male',25,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1244,'Dibden, Mr. William','male',18,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1245,'Herman, Mr. Samuel','male',49,1,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1246,'Dean, Miss. Elizabeth Gladys Millvina""','female',0.17,1,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1247,'Julian, Mr. Henry Forbes','male',50,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1248,'Brown, Mrs. John Murray (Caroline Lane Lamson)','female',59,2,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1249,'Lockyer, Mr. Edward','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1250,'O'Keefe, Mr. Patrick','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1251,'Lindell, Mrs. Edvard Bengtsson (Elin Gerda Persson)','female',30,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1252,'Sage, Master. William Henry','male',14.5,8,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1253,'Mallet, Mrs. Albert (Antoinette Magnin)','female',24,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1254,'Ware, Mrs. John James (Florence Louise Long)','female',31,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1255,'Strilic, Mr. Ivan','male',27,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1256,'Harder, Mrs. George Achilles (Dorothy Annan)','female',25,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1257,'Sage, Mrs. John (Annie Bullen)','female',,1,9);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1258,'Caram, Mr. Joseph','male',,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1259,'Riihivouri, Miss. Susanna Juhantytar Sanni""','female',22,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1260,'Gibson, Mrs. Leonard (Pauline C Boeson)','female',45,0,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1261,'Pallas y Castello, Mr. Emilio','male',29,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1262,'Giles, Mr. Edgar','male',21,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1263,'Wilson, Miss. Helen Alice','female',31,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1264,'Ismay, Mr. Joseph Bruce','male',49,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1265,'Harbeck, Mr. William H','male',44,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1266,'Dodge, Mrs. Washington (Ruth Vidaver)','female',54,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1267,'Bowen, Miss. Grace Scott','female',45,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1268,'Kink, Miss. Maria','female',22,2,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1269,'Cotterill, Mr. Henry Harry""','male',21,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1270,'Hipkins, Mr. William Edward','male',55,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1271,'Asplund, Master. Carl Edgar','male',5,4,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1272,'O'Connor, Mr. Patrick','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1273,'Foley, Mr. Joseph','male',26,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1274,'Risien, Mrs. Samuel (Emma)','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1275,'McNamee, Mrs. Neal (Eileen O'Leary)','female',19,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1276,'Wheeler, Mr. Edwin Frederick""','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1277,'Herman, Miss. Kate','female',24,1,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1278,'Aronsson, Mr. Ernst Axel Algot','male',24,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1279,'Ashby, Mr. John','male',57,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1280,'Canavan, Mr. Patrick','male',21,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1281,'Palsson, Master. Paul Folke','male',6,3,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1282,'Payne, Mr. Vivian Ponsonby','male',23,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1283,'Lines, Mrs. Ernest H (Elizabeth Lindsey James)','female',51,0,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1284,'Abbott, Master. Eugene Joseph','male',13,0,2);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1285,'Gilbert, Mr. William','male',47,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1286,'Kink-Heilmann, Mr. Anton','male',29,3,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1287,'Smith, Mrs. Lucien Philip (Mary Eloise Hughes)','female',18,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1288,'Colbert, Mr. Patrick','male',24,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1289,'Frolicher-Stehli, Mrs. Maxmillian (Margaretha Emerentia Stehli)','female',48,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1290,'Larsson-Rondberg, Mr. Edvard A','male',22,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1291,'Conlon, Mr. Thomas Henry','male',31,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1292,'Bonnell, Miss. Caroline','female',30,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1293,'Gale, Mr. Harry','male',38,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1294,'Gibson, Miss. Dorothy Winifred','female',22,0,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1295,'Carrau, Mr. Jose Pedro','male',17,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1296,'Frauenthal, Mr. Isaac Gerald','male',43,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1297,'Nourney, Mr. Alfred (Baron von Drachstedt")"','male',20,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1298,'Ware, Mr. William Jeffery','male',23,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1299,'Widener, Mr. George Dunton','male',50,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1300,'Riordan, Miss. Johanna Hannah""','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1301,'Peacock, Miss. Treasteall','female',3,1,1);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1302,'Naughton, Miss. Hannah','female',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1303,'Minahan, Mrs. William Edward (Lillian E Thorpe)','female',37,1,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1304,'Henriksson, Miss. Jenny Lovisa','female',28,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1305,'Spector, Mr. Woolf','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1306,'Oliva y Ocana, Dona. Fermina','female',39,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1307,'Saether, Mr. Simon Sivertsen','male',38.5,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1308,'Ware, Mr. Frederick','male',,0,0);
INSERT INTO passenger (id, name, sex, age, sibsp, parch) VALUES (1309,'Peter, Master. Michael J','male',,1,1);
