CREATE TABLE cabin(
    id  SERIAL NOT NULL PRIMARY KEY,
    cabin_name VARCHAR(50)
);
INSERT INTO cabin(cabin_name) VALUES ('A11');
INSERT INTO cabin(cabin_name) VALUES ('A18');
INSERT INTO cabin(cabin_name) VALUES ('A21');
INSERT INTO cabin(cabin_name) VALUES ('A29');
INSERT INTO cabin(cabin_name) VALUES ('A34');
INSERT INTO cabin(cabin_name) VALUES ('A9');
INSERT INTO cabin(cabin_name) VALUES ('B10');
INSERT INTO cabin(cabin_name) VALUES ('B11');
INSERT INTO cabin(cabin_name) VALUES ('B24');
INSERT INTO cabin(cabin_name) VALUES ('B26');
INSERT INTO cabin(cabin_name) VALUES ('B36');
INSERT INTO cabin(cabin_name) VALUES ('B41');
INSERT INTO cabin(cabin_name) VALUES ('B45');
INSERT INTO cabin(cabin_name) VALUES ('B51 B53 B55');
INSERT INTO cabin(cabin_name) VALUES ('B52 B54 B56');
INSERT INTO cabin(cabin_name) VALUES ('B57 B59 B63 B66');
INSERT INTO cabin(cabin_name) VALUES ('B58 B60');
INSERT INTO cabin(cabin_name) VALUES ('B61');
INSERT INTO cabin(cabin_name) VALUES ('B69');
INSERT INTO cabin(cabin_name) VALUES ('B71');
INSERT INTO cabin(cabin_name) VALUES ('B78');
INSERT INTO cabin(cabin_name) VALUES ('C101');
INSERT INTO cabin(cabin_name) VALUES ('C105');
INSERT INTO cabin(cabin_name) VALUES ('C106');
INSERT INTO cabin(cabin_name) VALUES ('C116');
INSERT INTO cabin(cabin_name) VALUES ('C130');
INSERT INTO cabin(cabin_name) VALUES ('C132');
INSERT INTO cabin(cabin_name) VALUES ('C22 C26');
INSERT INTO cabin(cabin_name) VALUES ('C23 C25 C27');
INSERT INTO cabin(cabin_name) VALUES ('C28');
INSERT INTO cabin(cabin_name) VALUES ('C31');
INSERT INTO cabin(cabin_name) VALUES ('C32');
INSERT INTO cabin(cabin_name) VALUES ('C39');
INSERT INTO cabin(cabin_name) VALUES ('C46');
INSERT INTO cabin(cabin_name) VALUES ('C51');
INSERT INTO cabin(cabin_name) VALUES ('C53');
INSERT INTO cabin(cabin_name) VALUES ('C54');
INSERT INTO cabin(cabin_name) VALUES ('C55 C57');
INSERT INTO cabin(cabin_name) VALUES ('C6');
INSERT INTO cabin(cabin_name) VALUES ('C62 C64');
INSERT INTO cabin(cabin_name) VALUES ('C7');
INSERT INTO cabin(cabin_name) VALUES ('C78');
INSERT INTO cabin(cabin_name) VALUES ('C80');
INSERT INTO cabin(cabin_name) VALUES ('C85');
INSERT INTO cabin(cabin_name) VALUES ('C86');
INSERT INTO cabin(cabin_name) VALUES ('C89');
INSERT INTO cabin(cabin_name) VALUES ('C97');
INSERT INTO cabin(cabin_name) VALUES ('D');
INSERT INTO cabin(cabin_name) VALUES ('D10 D12');
INSERT INTO cabin(cabin_name) VALUES ('D15');
INSERT INTO cabin(cabin_name) VALUES ('D19');
INSERT INTO cabin(cabin_name) VALUES ('D21');
INSERT INTO cabin(cabin_name) VALUES ('D22');
INSERT INTO cabin(cabin_name) VALUES ('D28');
INSERT INTO cabin(cabin_name) VALUES ('D30');
INSERT INTO cabin(cabin_name) VALUES ('D34');
INSERT INTO cabin(cabin_name) VALUES ('D37');
INSERT INTO cabin(cabin_name) VALUES ('D38');
INSERT INTO cabin(cabin_name) VALUES ('D40');
INSERT INTO cabin(cabin_name) VALUES ('D43');
INSERT INTO cabin(cabin_name) VALUES ('E31');
INSERT INTO cabin(cabin_name) VALUES ('E34');
INSERT INTO cabin(cabin_name) VALUES ('E39 E41');
INSERT INTO cabin(cabin_name) VALUES ('E45');
INSERT INTO cabin(cabin_name) VALUES ('E46');
INSERT INTO cabin(cabin_name) VALUES ('E50');
INSERT INTO cabin(cabin_name) VALUES ('E52');
INSERT INTO cabin(cabin_name) VALUES ('E60');
INSERT INTO cabin(cabin_name) VALUES ('F');
INSERT INTO cabin(cabin_name) VALUES ('F E46');
INSERT INTO cabin(cabin_name) VALUES ('F E57');
INSERT INTO cabin(cabin_name) VALUES ('F G63');
INSERT INTO cabin(cabin_name) VALUES ('F2');
INSERT INTO cabin(cabin_name) VALUES ('F33');
INSERT INTO cabin(cabin_name) VALUES ('F4');
INSERT INTO cabin(cabin_name) VALUES ('G6');
